# .golangci.yml
version: '2'
run:
  go: '1.24'
  issues-exit-code: 1
  tests: false
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - mnd
    - nakedret
    - nlreturn
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - tagliatelle
    - unconvert
    - unparam
    - unused
    - whitespace
    - wrapcheck
  settings:
    copyloopvar:
      check-alias: true
    cyclop:
      max-complexity: 10
      package-average: 0.5
    decorder:
      dec-order:
        - type
        - const
        - var
        - func
    depguard:
      rules:
        logger:
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: logging is allowed only by github.com/uber-go/zap
            - pkg: log
              desc: logging is allowed only by github.com/uber-go/zap
    dupl:
      threshold: 100
    funlen:
      lines: -1
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - commentedOutCode
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 20
    gosec:
      excludes:
        - G115
    govet:
      disable:
        - sigchanyzer
        - structtag
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 124
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
      ignored-numbers:
        - '0666'
        - '0600'
        - '0644'
        - '0755'
        - '0777'
        - '0700'
        - '42'
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
        - '8'
        - '16'
        - '32'
      ignored-files:
        - magic1_.+\.go$
      ignored-functions:
        - ^math\.
        - ^http\.StatusText$
    nlreturn:
      block-size: 2
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    revive:
      rules:
        - name: unexported-return
          disabled: true
        - name: unused-parameter
        - name: cyclomatic
          arguments:
            - 20
          severity: error
          disabled: false
        - name: struct-tag
          disabled: true
    tagliatelle:
      case:
        rules:
          avro: snake
          bson: camel
          env: upperSnake
          envconfig: upperSnake
          json: camel
          mapstructure: kebab
          xml: camel
          yaml: camel
        use-field-name: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: pkg/golinters/errcheck.go
        text: 'SA1019: errCfg.Exclude is deprecated: use ExcludeFunctions instead'
      - path: pkg/commands/run.go
        text: 'SA1019: lsc.Errcheck.Exclude is deprecated: use ExcludeFunctions instead'
      - path: pkg/commands/run.go
        text: 'SA1019: e.cfg.Run.Deadline is deprecated: Deadline exists for historical compatibility and should not be used.'
      - path: pkg/golinters/gofumpt.go
        text: 'SA1019: settings.LangVersion is deprecated: use the global `run.go` instead.'
      - path: pkg/golinters/staticcheck_common.go
        text: 'SA1019: settings.GoVersion is deprecated: use the global `run.go` instead.'
      - path: pkg/lint/lintersdb/manager.go
        text: 'SA1019: (.+).(GoVersion|LangVersion) is deprecated: use the global `run.go` instead.'
      - path: pkg/golinters/unused.go
        text: 'rangeValCopy: each iteration copies 160 bytes \(consider pointers or indexing\)'
      - path: test/(fix|linters)_test.go
        text: string `gocritic.go` has 3 occurrences, make it a constant
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - etc/
      - test/testdata_etc/
      - app/gmodels/
      - app/gdal/
      - internal/cache/
      - internal/renameio/
      - internal/robustio/
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
        - pattern: a[b:len(a)]
          replacement: a[b:]
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint
  exclusions:
    generated: lax
    paths:
      - etc/
      - test/testdata_etc/
      - app/gmodels/
      - app/gdal/
      - internal/cache/
      - internal/renameio/
      - internal/robustio/
      - third_party$
      - builtin$
      - examples$
